swagger: "2.0"
info:
  version: "0.0.1"
  title: PIC DIAN
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of the responses to the client (Accepts)
produces:
  - application/json
  - application/xml
paths:
  /encriptar:
    # binds a127 app logic to a route
    x-swagger-router-controller: util
    post:
      description: Encripta el texto enviado
      # used as the method name of the controller
      operationId: encriptar
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GenericResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /desencriptar:
    # binds a127 app logic to a route
    x-swagger-router-controller: util
    post:
      description: Desencripta el texto enviado
      # used as the method name of the controller
      operationId: desencriptar
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GenericResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /identificacionUsuario:
    # binds a127 app logic to a route
    x-swagger-router-controller: manejo_usuarios_controller
    post:
      description: Controla el inicio de sesión y verificación de roles
      # used as the method name of the controller
      operationId: identificacionUsuario
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GenericResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /crearUsuario:
    # binds a127 app logic to a route
    x-swagger-router-controller: manejo_usuarios_controller
    post:
      description: Controla la creación de usuarios del sistema
      # used as the method name of the controller
      operationId: crearUsuario
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GenericResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /registrarPreguntas:
    # binds a127 app logic to a route
    x-swagger-router-controller: preguntas_controller
    post:
      description: Controla la creación de usuarios del sistema
      # used as the method name of the controller
      operationId: registrarPreguntas
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GenericResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /registrarPregunta:
    # binds a127 app logic to a route
    x-swagger-router-controller: preguntas_controller
    post:
      description: Controla la creación de usuarios del sistema
      # used as the method name of the controller
      operationId: registrarPregunta
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GenericResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse" 
  /obtenerProcesos:
    # binds a127 app logic to a route
    x-swagger-router-controller: cuestionario_controller
    post:
      description: Controla la creación de usuarios del sistema
      # used as the method name of the controller
      operationId: obtenerProcesos
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GenericResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /obtenerPreguntas:
      # binds a127 app logic to a route
      x-swagger-router-controller: preguntas_controller
      post:
        description: Controla la creación de usuarios del sistema
        # used as the method name of the controller
        operationId: obtenerPreguntas
        responses:
          "200":
            description: Success
            schema:
              # a pointer to a definition
              $ref: "#/definitions/GenericResponse"
          # responses may fall through to errors
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  GenericResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
